"""add new fields settings

Revision ID: 2fc3860ac343
Revises: b3b097daf4fe
Create Date: 2024-07-24 22:09:24.575712

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fc3860ac343"
down_revision: Union[str, None] = "b3b097daf4fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    op.alter_column("users", "firstname", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "lastname", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint("users_phone_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_phone_key", "users", ["phone"])
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "lastname", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "firstname", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "username")
    # ### end Alembic commands ###
