"""empty migration

Revision ID: e4642177c26e
Revises: 
Create Date: 2024-07-14 15:35:01.995882

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4876c86fce38"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
